# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
