# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160720_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
        migrations.AddField(
            model_name='myuser',
            name='fb_id',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='fb_id'),
        ),
    ]
