# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160723_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fb_id',
            field=models.BigIntegerField(unique=True, verbose_name='fb_id'),
        ),
    ]
