# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20160724_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(max_length=300, upload_to=''),
        ),
    ]
