# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20160727_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
