# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20160727_0408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together=set([('user_id', 'round_id')]),
        ),
    ]
