# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20160727_1906'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roundnickname',
            unique_together=set([('user_id', 'round_id'), ('round_id', 'nickname_id')]),
        ),
    ]
