# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20160728_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pick_id',
            new_name='pick',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='round_id',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='roundnickname',
            old_name='nickname_id',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='roundnickname',
            old_name='round_id',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='roundnickname',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set([('user', 'comment')]),
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together=set([('user', 'round')]),
        ),
        migrations.AlterUniqueTogether(
            name='roundnickname',
            unique_together=set([('round', 'nickname'), ('user', 'round')]),
        ),
    ]
